"""Typed records used by the Research OS data layer.

The storage layer intentionally keeps the domain open ended: an entity's
``entity_type`` can be one of the built-in types (``Paper``, ``Claim`` ...)
or a project-specific type.  These small dataclasses make the API pleasant for
the UI while retaining that flexibility.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
from typing import Any, Mapping


def _mapping_value(value: Any) -> dict[str, Any]:
    """Coerce a structured payload from a mapping or JSON text.

    CSV/JSON importers often hand the domain layer a serialized object.  A
    plain ``dict(serialized_string)`` raises a cryptic error (or, for some
    iterables, produces surprising keys), so normalize that boundary here.
    Invalid/non-object JSON intentionally degrades to an empty mapping; the
    persistence layer can then validate the rest of the record normally.
    """
    if isinstance(value, Mapping):
        return dict(value)
    if isinstance(value, str):
        try:
            decoded = json.loads(value)
        except (TypeError, ValueError):
            return {}
        return dict(decoded) if isinstance(decoded, Mapping) else {}
    return {}


ENTITY_TYPES = (
    "Paper",
    "Claim",
    "Evidence",
    "Concept",
    "Question",
    "Hypothesis",
    "Experiment",
    "Dataset",
    "Artifact",
    "Result",
    "Decision",
    "Idea",
    "Task",
    "DailyLog",
)


@dataclass(slots=True)
class Entity:
    """A node in the research graph.

    ``data`` contains structured fields specific to the type.  It is kept as
    JSON in SQLite, so new fields can be introduced without schema migrations.
    ``id`` is optional on input and generated by the store when omitted.
    """

    entity_type: str
    title: str
    content: str = ""
    data: dict[str, Any] = field(default_factory=dict)
    id: str | None = None
    created_at: str | None = None
    updated_at: str | None = None
    version: int = 1

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "entity_type": self.entity_type,
            "title": self.title,
            "content": self.content,
            "data": dict(self.data),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "version": self.version,
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "Entity":
        return cls(
            id=value.get("id"),
            entity_type=str(value.get("entity_type") or value.get("type") or "Concept"),
            title=str(value.get("title") or ""),
            content=str(value.get("content") or ""),
            data=_mapping_value(value.get("data")),
            created_at=value.get("created_at"),
            updated_at=value.get("updated_at"),
            version=int(value.get("version") or 1),
        )


@dataclass(slots=True)
class Relation:
    """A directed, typed edge between two entities."""

    source_id: str
    relation_type: str
    target_id: str
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str | None = None
    created_at: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "source_id": self.source_id,
            "relation_type": self.relation_type,
            "target_id": self.target_id,
            "metadata": dict(self.metadata),
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "Relation":
        return cls(
            id=value.get("id"),
            source_id=str(value.get("source_id") or value.get("source") or ""),
            relation_type=str(value.get("relation_type") or value.get("relation") or ""),
            target_id=str(value.get("target_id") or value.get("target") or ""),
            metadata=_mapping_value(value.get("metadata")),
            created_at=value.get("created_at"),
        )


@dataclass(slots=True)
class SearchHit:
    """A search result with a lightweight relevance score."""

    entity: Entity
    rank: float = 0.0
    snippet: str = ""

    def to_dict(self) -> dict[str, Any]:
        result = self.entity.to_dict()
        result.update({"rank": self.rank, "snippet": self.snippet})
        return result
